flowchart TD
    A[Full Team Meet] -->B[Idea Finalisation]
    A --> C[Milestones Discussion]
    A --> R[Documentation Team]
    
    B --> D[Research Team]
    B --> E[Electrical Team]
    B --> F[Fabrication Team]
    
    F --> G[Autodesk Inventor]
    F --> H[Milestones Finalisation]
    
    D --> I[Content Preparation]
    D --> J[Solvent Decision]
    D --> K[Brainstorming of Idea]
    D --> L[Testing of Solvents]
    
    E --> M[Roller]
    E --> N[Soap Water Sprinkler]
    E --> O[Scrubber]
    E --> P[Blower]
    E --> Q[Dryer]

    R --> |Plan A|T[Latex Team]
    R --> |Plan B|S[ASCII Doc Team]
    R --> |Plan C|U[Markdown Team]
    R --> V[Mindmaps and Drawing Team]
    R --> W[Project Managemnt Team]
    R --> X[Content Team]

  